### ISSUE TITLE
Unable to download model from baidu

### ISSUE THREAD

**Issue by inderjitsinghtrantor** [chizhanyuefeng/DB-tf#1]
Request you to kindly also host the model on gdrive etc, as baidu requires phone number to register the same has to be from china, making the model inaccessible to anyone outside of china.

**Comment by deepseek** [comment]
@chizhanyuefeng Upload the ResNet-50 & ResNet-18 models.

**Comment by chizhanyuefeng** [comment]
@deepseek @inderjitsinghtrantor ResNet-50 model is upload to goole drive
